[package]
name = "dronegowski_utils"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git", features = ["debug", "serialize"] }
dronegowski_internal = { path = "crates/dronegowski_internal" }